### ISSUE TITLE
关于 - (CGSize)pictureView:(ESPictureBrowser *)pictureBrowser imageSizeForIndex:(NSInteger)index

### ISSUE THREAD

**Issue by 02VC7** [EnjoySR/ESPictureBrowser#1]
此方法在大多数情况下可用，但当加载的是网络图片时无法预知大小导致不能正确显示。个人建议加载完后再根据图片大小自行设置。

**Comment by EnjoySR** [comment]
OK.改好了回复你

**Comment by EnjoySR** [comment]
@02VC7 
已做如下改动：
将设置图片大小的代理方法置为可选，如果不实现该方法：
- a.查看是否实现默认图片的方法，如果有，获取默认图片的大小设置为图片的大小
- b.如果 a 不满足，会去判断对应索引的 view 是否是一个 imageView，如果是设置 imageView.image 的大小
- c.如果 b 不满足，默认宽高为屏幕高度
- d.最终都会在高清图片下载完成之后去计算图片的大小调整界面
